version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wodfeeder
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - wf_local_network

  web-server:
    depends_on:
      - db
    image: library/gradle:6.6.1-jdk14
    container_name: web-server
    working_dir: /web-server
    ports:
      - 8080:8080
    volumes:
      - ../web-server:/web-server
    entrypoint: gradle bootRun --no-daemon
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/wodfeeder
      - DATABASE_USERNAME=gabriel
      - DATABASE_PASSWORD=not_empty
      - JWT_SECRET='dev-super-duper-secret'
    networks:
      - wf_local_network

networks:
  wf_local_network:
    driver: bridge
