name: Deploy web-server to Heroku

on:
  push:
    paths:
      - "web-server/**"
      - ".github/workflows/web-server.yml"

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_DB: "${{ secrets.DATABASE_TEST }}"
          POSTGRES_USER: "${{ secrets.DATABASE_USERNAME_TEST }}"
          POSTGRES_PASSWORD: "$ {{secrets.DATABASE_PASSWORD_TEST }}"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.2
        with:
          java-version: '14'

      - name: Run Tests
        run: ./gradlew web-server:test -x generateOpenApiDocs
        env:
          JWT_SECRET: "${{ secrets.JWT_SECRET_TEST }}"
          DATABASE_URL: "jdbc:postgresql://localhost:5432/${{ secrets.DATABASE_TEST }}"
          DATABaSE_USERNAME: "${{ secrets.DATABASE_USERNAME_TEST }}"
          DATABASE_PASSWORD: "${{secrets.DATABASE_PASSWORD_TEST }}"

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Add web-server remote origin
        run: git remote add heroku-web-server https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git

      - name: Deploy web-server to Heroku
        run: git push heroku-web-server `git subtree split --prefix web-server master`:refs/heads/master --force
