name: Deploy web-client to Heroku

on:
  push:
    paths:
      - "web-client/**"
      - ".github/workflows/web-client/**"
      - ".github/workflows/web-client.yml"

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Java Version
        uses: actions/setup-java@v1.4.2
        with:
          java-version: '14'

      - name: Set Node Version
        uses: actions/setup-node@v1.4.3
        with: 
          node-version: '14.5.0'

      - name: Install dependencies
        run: npm install
        working-directory: ./web-client

      - name: Run Lint
        run: npm run lint
        working-directory: ./web-client

      - name: Run Tests
        run: npm run test
        working-directory: ./web-client

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Setting the App Version on Heroku
        run: ./web-client-version.sh
        working-directory: TOKEN=${{ secrets.HEROKU_API_TOKEN }}; ./.github/workflows/web-client

      - name: Add web-client remote origin
        run: git remote add heroku-web-client https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_WEB_CLIENT_APP_NAME }}.git

      - name: Deploy web-client to Heroku
        run: git push heroku-web-client `git subtree split --prefix web-client master`:refs/heads/master --force
