name: Deploy web-server to Heroku

on:
  push:
    branches:
      - master
    paths:
      - "webserver/**"
      - ".github/workflows/web-server.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Add web-server remote origin
        run: git remote add heroku-web-server https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git
      - name: Deploy web-server to Heroku
        run: git push heroku-web-server `git subtree split --prefix web-server master`:refs/heads/master --force