name: Deploy $APP_NAME to Heroku

env:
  APP_NAME: web-server

on:
  push:
    branches:
      - master
    paths:
      - "webserver/**"
      - ".github/workflows/$APP_NAME.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14'
      - name: Add $APP_NAME remote origin
        run: git remote add heroku-$APP_NAME https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_BACKEND_APP_NAME }}.git
      - name: Deploy $APP_NAME to Heroku
        run: git push heroku-$APP_NAME `git subtree split --prefix $APP_NAME master`:refs/heads/master --force